%YAML:1.0

#--------------------------------------------------------------------------------------------
# Localization Parameters.       
#--------------------------------------------------------------------------------------------

# Run localization every LOCALIZATION_PER_FRAME frames
LOCALIZATION_PER_FRAME: 3

# Number of images to skip prior to localization. Set to 0 if no skip.
SKIPPED_IMAGES: 440

# 2018-06-23-12-46-26_0_z-filtered_4m.pcd is map for 2018-06-23-12-46-26_0.bag 
LIDAR_MAP_FILEPATH: "src/stereo_localization/res/2018-06-23-12-46-26_0_z-filtered_4m.pcd" 

NELDER_MEAD_ITERS: 150
SCENE_SIZE: 40
X_ROI: 30
Y_ROI: 60

#--------------------------------------------------------------------------------------------
# SGBM Parameters.       
#--------------------------------------------------------------------------------------------

SGBM.n_disparities: 64
SGBM.sad_window_size: 11
SGBM.pre_filter_cap: 15

#--------------------------------------------------------------------------------------------
# Camera Parameters.
# Camera.fx, .fy, etc must be the same as in LEFT.P
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters
Camera.fx: 699.865
Camera.fy: 699.865
Camera.cx: 603.58
Camera.cy: 332.778
Camera.width: 640
Camera.height: 360 

LEFT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]

LEFT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [336.93487548828125, 0.0, 307.74444580078125, 0.0, 336.93487548828125, 165.8551483154297, 0.0, 0.0, 1.0]
LEFT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

LEFT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [336.93487548828125, 0.0, 307.74444580078125, 0.0, 0.0, 336.93487548828125, 165.8551483154297, 0.0, 0.0, 0.0, 1.0, 0.0]


RIGHT.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]
RIGHT.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [336.93487548828125, 0.0, 307.74444580078125, 0.0, 336.93487548828125, 165.8551483154297, 0.0, 0.0, 1.0]

RIGHT.R:  !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

RIGHT.P:  !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [336.93487548828125, 0.0, 307.74444580078125, -40.432186126708984, 0.0, 336.93487548828125, 165.8551483154297, 0.0, 0.0, 0.0, 1.0, 0.0]

#--------------------------------------------------------------------------------------------
# Extrinsic Parameters.     	  
#--------------------------------------------------------------------------------------------

# extrinsics for 2018-06-23-12-46-26_0.bag
LIDAR_TO_CAM.rot: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.00985576, -0.99970535, -0.02218292,-0.00230424,  0.02216124, -0.99975175, 0.99994878,  0.00990443, -0.00208514]
LIDAR_TO_CAM.trans: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.08659319, -0.3958742,  -0.92898518]

#--------------------------------------------------------------------------------------------
# Mapping Parameters
#--------------------------------------------------------------------------------------------

# If current scan's translation with previous kept scan does not exceed min_shift, throw away
MAPPING.min_shift: 4.0 

# Number of scans to add to map 	
MAPPING.added_num: 46

MAPPING.lidar_pose_filepath: ""
